//! Build script: XOR-obfuscate the embedded system prompts.
//!
//! The prompts are the product's prompt-engineering core. Shipping them as
//! `include_str!` literals puts the full plaintext in the binary's `.rodata`,
//! so `strings aizen(.exe)` lifts them verbatim. Here we XOR each prompt with a
//! per-build keystream and emit ciphertext byte arrays; the runtime
//! (`src/agent/mod.rs::obf`) decodes them once, lazily, into cached `String`s.
//!
//! This defeats casual and automated (`strings`) extraction. It does NOT stop a
//! determined reverse-engineer — the key ships in the binary, so anyone who
//! disassembles can recover the plaintext. No purely client-side scheme can do
//! better; only keeping the core server-side would.

use std::env;
use std::fs;
use std::path::Path;
use std::time::{SystemTime, UNIX_EPOCH};

fn main() {
    let files = [
        ("system_prompt.md", "SYSTEM_BASE_OBF"),
        ("system_prompt_strict.md", "SYSTEM_BASE_STRICT_OBF"),
    ];

    // Per-build keystream seed. Non-reproducible on purpose: the same plaintext
    // yields different ciphertext each build and the key is not a guessable
    // constant. Falls back to a fixed odd seed if the clock is unavailable.
    let seed = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_nanos() as u64)
        .unwrap_or(0x9E37_79B9_7F4A_7C15)
        | 1;

    // 64-byte key expanded from the seed with a splitmix64 PRNG.
    let mut key = [0u8; 64];
    let mut x = seed;
    for k in key.iter_mut() {
        x = x.wrapping_add(0x9E37_79B9_7F4A_7C15);
        let mut z = x;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        z ^= z >> 31;
        *k = (z & 0xFF) as u8;
    }

    let manifest = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let dest = Path::new(&out_dir).join("prompts_obf.rs");

    let mut gen = String::from("// @generated by build.rs — obfuscated system prompts.\n");
    gen.push_str(&format!(
        "pub static PROMPT_KEY: &[u8] = &{:?};\n",
        &key[..]
    ));

    for (file, ident) in files {
        println!("cargo:rerun-if-changed=src/agent/{file}");
        let path = Path::new(&manifest).join("src").join("agent").join(file);
        let bytes = fs::read(&path)
            .unwrap_or_else(|e| panic!("build.rs: cannot read {}: {e}", path.display()));
        let cipher: Vec<u8> = bytes
            .iter()
            .enumerate()
            .map(|(i, b)| b ^ key[i % key.len()])
            .collect();
        gen.push_str(&format!("pub static {ident}: &[u8] = &{cipher:?};\n"));
    }

    fs::write(&dest, gen).expect("build.rs: write prompts_obf.rs");
    println!("cargo:rerun-if-changed=build.rs");
}
